# appveyor file
# http://www.appveyor.com/docs/appveyor-yml

max_jobs: 1

shallow_clone: true

init:
  - git config --global core.autocrlf true

image:
  - Visual Studio 2017

environment:
  PLATFORM: windows-10-store
  JUST_BUILD: --justBuild
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "10"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version
  - node --version
  - npm install -g cordova-paramedic@https://github.com/apache/cordova-paramedic.git
  - npm install -g cordova

build: off

test_script:
  - cordova-paramedic --config pr\%PLATFORM% --plugin . %JUST_BUILD%
